[default]
SQLALCHEMY_DATABASE_URI = 'postgresql://user:password@localhost:5432/API-test'
SQLALCHEMY_TRACK_MODIFICATIONS = 'False'

EXTENSIONS = [
    "extension.database",
    "extension.commands",
    "resources",
]
